### ISSUE TITLE
Segmentation fault occurs when analyzing APK

### ISSUE THREAD

**Issue by zinwang** [Shuriken-Group/Shuriken-Analyzer#117]
**Description:**

Hi, I encountered a segmentation fault when analyzing [this APK](https://github.com/quark-engine/apk-samples/blob/master/malware-samples/Ahmyth.apk) with Shuriken.

```
zsh: segmentation fault (core dumped)  shuriken-dump Ahmyth.apk
```

**Steps to reproduce:**

1. Install Shuriken([bd50913](https://github.com/Shuriken-Group/Shuriken-Analyzer/commit/bd509135ddcad56f6c07c700c6766dc3170adcbc)) with CMake.
    ```
    cmake -S . -B build/ -DCMAKE_BUILD_TYPE=Release  && cmake --build build/ -j && sudo cmake --install build/
    ```

2. Analyze the APK with shuriken-dump.
    ```
    shuriken-dump Ahmyth.apk                                       
    ```

**Environment:**

> CMake Version: 3.29.3
> Operating System: Linux 6.6.46-1-MANJARO x86_64

Let me know if you need more details.

**Comment by jeppojeps** [comment]
taking a look

**Comment by badumbatish** [comment]
can you uninstall, rebuild and reinstall your command with -DCMAKE_BUILD_TYPE=Debug 
```
cmake --build build --target uninstall
cmake -S . -B build/ -DCMAKE_BUILD_TYPE=Debug  && cmake --build build/ -j && sudo cmake --install build/
```
and rerun this through [catchsegv](https://www.commandlinux.com/man-page/man1/catchsegv.1.html), a stacktrace from your own environment would be very helpful @zinwang

**Comment by zinwang** [comment]
@badumbatish Sure! Here is the catchsegv output for shuriken-dump analyzing Ahmyth.apk. 
(Using the latest commit of Shuriken: [5ad9e86](https://github.com/Shuriken-Group/Shuriken-Analyzer/commit/5ad9e86362bce295b404776a1e9ca8021999c4a5))
https://gist.github.com/zinwang/e79714d0c8d4ec786ecec53a24990f03
