### ISSUE TITLE
Start research in MLIR

### ISSUE THREAD

**Issue by Fare9** [Shuriken-Group/Shuriken-Analyzer#54]
We need to start researching about MLIR to know how to create our new IR, we can start looking to the old IR from Kunai, MjolnIR: [MjolnIR](https://github.com/Fare9/KUNAI-static-analyzer/tree/refactoring/kunai-lib/MjolnIR). Let's use this issue for providing all the possible documentation and start giving ideas for the new IR.

**Comment by Fare9** [comment]
[MLIR — A Global Optimization and Dataflow Analysis](https://www.jeremykun.com/2023/11/15/mlir-a-global-optimization-and-dataflow-analysis/)

**Comment by badumbatish** [comment]
https://www.jeremykun.com/2023/08/21/mlir-defining-a-new-dialect/

**Comment by Fare9** [comment]
I had this as documentation of the dalvik instructions mapped to different instructions from different dialects: https://github.com/Fare9/KUNAI-static-analyzer/blob/refactoring/kunai-lib/internal-doc/MJOLNIR/dalvik_opcodes.md

**Comment by Fare9** [comment]
In Java, the exceptions are represented as a list with information about the exceptions from the method, where they start, where they end, and which block is their handler, as well as a string indicating which exception is handled (in the bytecode level of Java). I like ASM documentation because it is easy to understand for this since they represent each Try/Catch with a `TryCatchNode` object: https://asm.ow2.io/javadoc/org/objectweb/asm/tree/TryCatchBlockNode.html

In MLIR, and more specifically in Kunai I used the `mlir::Block` class from MLIR: https://github.com/Fare9/KUNAI-static-analyzer/blob/refactoring/kunai-lib/MjolnIR/include/MjolnIR/Lifter/MjolnIRLifter.hpp#L84. But I think if we want to support  doing a recompilation of the IR we will need that information present somewhere in the blocks, so my idea would be to extend the current `mlir::Block` providing that information, something like:

```cpp
class Block {
    bool is_try;
    bool is_catch;
    std::vector<std::string> exceptions;
    // if it is a try, maybe we can try to keep a list of catch blocks, but maybe not needed
    std::vector<shuriken::Block*> catch_blocks;
}
```

With this, once we dump it to a format that a tool like [Smali](https://github.com/JesusFreke/smali) understands, we can directly print the block in the next way:

```
if (block.isTry())
    std::cout << "try:\n"';
else if (block.isCatch()) {
    std::cout << "catch ";
    for (auto & exception : block.exceptions()) 
        std::cout << exception << "|";
    std::cout << ":\n"
}
// continue printing the code
}
```

The previous code wouldn't work, but it is just an idea about how to make our life easier with try/catch nodes, including a bit of metadata in those blocks.

Anyway, we have to do this in tablegen, it is a bit weirdo, but once we get use to work with it, we can probably add more and more dialects whenever we need them.
