### ISSUE TITLE
ValueError occurred when accessing `hdvmmethod_t` from `dvmdisassembled_method_t` using Python API

### ISSUE THREAD

**Issue by haeter525** [Shuriken-Group/Shuriken-Analyzer#87]
**Describe the bug**

Hello there! I was trying to get the raw bytes of bytecodes using the Python API, so I accessed the `hdvmmethod_t` object from the `method_t` field of `dvmdisassembled_method_t`. Unfortunately, a ValueError occurred.

**To Reproduce**

1. Put [the APK](https://github.com/quark-engine/apk-samples/raw/refs/heads/master/malware-samples/13667fe3b0ad496a0cd157f34b7e0c991d72a4db.apk) in the current working directory.
2. Run the following script.

```python
from shuriken import *

apk = Apk("13667fe3b0ad496a0cd157f34b7e0c991d72a4db.apk", True)

disassembledMethod = apk.get_disassembled_method_from_apk(
	"Lcom/example/google/service/ContactsHelper;->getSIMContacts()V"
)
methodId = disassembledMethod.method_id.contents
print(methodId.method_name)
```

3. ValueError occurs.

```
Traceback (most recent call last):
  File "/workspaces/apk_samples/malware-samples/test.py", line 8, in <module>
    methodId = disassembledMethod.method_id.contents
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: NULL pointer access
```

**Expected behavior**

With the following script, I found the `hdvmmethod_t` object is accessible from `hdvmclass_t`. 

```python
from shuriken import *

apk = Apk("13667fe3b0ad496a0cd157f34b7e0c991d72a4db.apk", True)

clazz = apk.get_hdvmclass_from_dex_by_index("classes.dex", 346) # Lcom/example/google/service/ContactsHelper;

methodId = clazz.direct_methods[5]
print(methodId.method_name) # print b'getSIMContacts'
```

Hence, I think the `hdvmmethod_t` object did exist, and accessing the `method_t` field of `dvmdisassembled_method_t` should get this object. But please correct me if I am missing something.

**Comment by jeppojeps** [comment]
Will try to give it a check today. Thanks for reporting.

**Comment by jeppojeps** [comment]
A quick update, I have made some investigation and it appears that the method you are seeking for is external, at least according to @Fare9 

![image](https://github.com/user-attachments/assets/b702ac13-6417-41a2-82a9-c96cb0e138fe)

you see that the disassembled object is properly returned but it contains a null pointer. That according to the architecture of the software should be external. @Fare9 will help to get through this.

**Comment by haeter525** [comment]
Hello. Thanks for the update! Is there any recent progress on this?

I took a closer look using `dexdump` and noticed that the method appears to have bytecodes in the APK. Following is how I found those bytecodes.

```
$> unzip 13667fe3b0ad496a0cd157f34b7e0c991d72a4db.apk -d 13667
$> dexdump -d 13667/classes.dex | grep -A 5 getSIMContacts
```

```
      name          : 'getSIMContacts'
      type          : '()V'
      access        : 0x0002 (PRIVATE)
      code          -
      registers     : 10
      ins           : 1
--
048980:                                        |[048980] com.example.google.service.ContactsHelper.getSIMContacts:()V
048990: 1203                                   |0000: const/4 v3, #int 0 // #0
048992: 5492 4e05                              |0001: iget-object v2, v9, Lcom/example/google/service/ContactsHelper;.mContext:Landroid/content/Context; // field@054e
048996: 6e10 8700 0200                         |0003: invoke-virtual {v2}, Landroid/content/Context;.getContentResolver:()Landroid/content/ContentResolver; // method@0087
04899c: 0c00                                   |0006: move-result-object v0
04899e: 1a02 ed0b                              |0007: const-string v2, "content://icc/adn" // string@0bed
--
048ae8: 7010 0814 0100                         |000a: invoke-direct {v1}, Lcom/example/google/service/ContactsHelper;.getSIMContacts:()V // method@1408
048aee: 5410 4d05                              |000d: iget-object v0, v1, Lcom/example/google/service/ContactsHelper;.mContacts:Ljava/util/ArrayList; // field@054d
048af2: 1100                                   |000f: return-object v0
048af4: 0d00                                   |0010: move-exception v0
048af6: 28fc                                   |0011: goto 000d // -0004
      catches       : 1
```

Could this mean it’s an internal method? Or is there something I might have overlooked? Just wanted to double-check. Thank you for looking into this!

**Comment by Fare9** [comment]
Hello, I will go over it this week, I didn't have the time last week, I will prioritize it. Thank you and sorry for the delay.

**Comment by Fare9** [comment]
Okay, I start working on this issue, this weekend you'll have news about it!
