### ISSUE TITLE
Encounter an error when importing the Python API installed by Pip

### ISSUE THREAD

**Issue by haeter525** [Shuriken-Group/Shuriken-Analyzer#99]
**Describe the bug**
Hi there. After installing Shuriken with Pip and importing the Python API, I got the following ImportError.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/.venv/lib/python3.12/site-packages/shuriken/__init__.py", line 53, in <module>
    raise ImportError("ERROR: fail to load the dynamic library")
ImportError: ERROR: fail to load the dynamic library
```

It seems like Pip didn't install the required library for Shuriken.

**Step to Reproduce**
1. Set up a Python virtual environment on Ubuntu 24.04.
	```
	python3 -m venv .venv && source .venv/bin/activate
	```
2. Install Shuriken with Pip.
	```
	pip install git+https://github.com/Fare9/Shuriken-Analyzer.git@main#subdirectory=shuriken/bindings/Python/
	```
3. Import the Python API.
	```
	python3 -c "from shuriken import *"
	```
4. The ImportError is raised.

**Additional Context**
By re-running the installation with the `-v` flag, pip reported a `cmake` command failed. So, I doubt if there were issues when Pip built Shuriken.

These are part of the Pip output. Starting from line 8, you can see a CMakeError.
```
$> pip install -v git+https://github.com/Fare9/Shuriken-Analyzer.git@main#subdirectory=shuriken/bindings/Python/

Using pip 24.0 from /.venv/lib/python3.12/site-packages/pip (python 3.12)
Collecting git+https://github.com/Fare9/Shuriken-Analyzer.git@main#subdirectory=shuriken/bindings/Python/
...
  -- Test option used and compilers path provided, compiling DEX files
  -- Path to DEX Folder: /tmp/pip-req-build-drpt5qd4/shuriken/build/tests/code/java/
  CMake Error at CMakeLists.txt:195 (install):                  <------------------------------- Line 8
    install DIRECTORY given no DESTINATION!

  -- Configuring incomplete, errors occurred!
  ERROR:__main__:Cmake build failed: Command '['cmake', '..', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  INFO:root:running install_lib
...

**Comment by badumbatish** [comment]
hi @haeter525, the issue should be resolved soon in #103 along with a dedicated ci for the python installer so it doesn't happen again on main branch.

The job for proof of installer working is https://github.com/Shuriken-Group/Shuriken-Analyzer/actions/runs/12207652888/job/34059470491
